apiVersion: v2
name: vault-unsealer
description: A Helm chart for Vault Unsealer in Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - vault
  - unsealer
  - hashicorp
home: https://github.com/hainamtvvt/unsealer.git
sources:
  - https://github.com/hainamtvvt/unsealer.git
maintainers:
  - name: namvh
    email: vhn@gmail.com
