{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unsealer
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: vault-unsealer
    chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            app: vault-unsealer
            release: {{ .Release.Name }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name | quote }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          containers:
            - name: vault-unsealer
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
              - python3
              - /app/vault-unsealer.py
              args:
              - --verbose
              env:
                - name: VAULT_NAMESPACE
                  value: {{ .Values.vault.namespace | quote }}
                - name: VAULT_LABEL_SELECTOR
                  value: {{ .Values.vault.labelSelector | quote }}
                - name: VAULT_TIMEOUT
                  value: {{ .Values.vault.timeout | quote }}
                - name: VAULT_USE_SERVICE
                  value: {{ .Values.vault.useService | quote }}
                - name: VERBOSE
                  value: {{ .Values.watcher.verbose | quote }}
                - name: VAULT_UNSEAL_KEY_1
                  valueFrom:
                    secretKeyRef:
                      name: vault-unsealer-keys
                      key: key1
                      optional: false

                - name: VAULT_UNSEAL_KEY_2
                  valueFrom:
                    secretKeyRef:
                      name: vault-unsealer-keys
                      key: key2
                      optional: false

                - name: VAULT_UNSEAL_KEY_3
                  valueFrom:
                    secretKeyRef:
                      name: vault-unsealer-keys
                      key: key3
                      optional: false
              {{- with .Values.watcher.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}
